{{/*
Expand the name of the chart.
*/}}
{{- define "gateway.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "gateway.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "gateway.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "gateway.labels" -}}
helm.sh/chart: {{ include "gateway.chart" . }}
{{ include "gateway.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "gateway.selectorLabels" -}}
app.kubernetes.io/name: {{ include "gateway.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "gateway.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "gateway.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
Create the name of the configmap to use
*/}}
{{- define "gateway.configMapName" -}}
{{- printf "%s-config" (include "gateway.fullname" .) }}
{{- end }}

{{/*
Create the name of the auto-generated TLS secret to use
*/}}
{{- define "gateway.tlsAutoGeneratedSecretName" -}}
{{- printf "%s-tls" (include "gateway.fullname" .) }}
{{- end }}

{{/*
Secret names holding the `tls.certificates.secrets` certificates, as a JSON array since include
returns a string. Callers decode it with fromJsonArray.
*/}}
{{- define "gateway.tlsProvidedSecretNames" -}}
{{- $fullname := include "gateway.fullname" . }}
{{- $names := list }}
{{- range $i, $secret := .Values.tls.certificates.secrets }}
{{- $names = append $names ($secret.name | default (printf "%s-tls-%d" $fullname $i)) }}
{{- end }}
{{- $names | toJson }}
{{- end }}

{{/*
Secret names holding every certificate the Gateway serves, as a JSON array since include
returns a string. Callers decode it with fromJsonArray.

The auto-generated certificate is always first when enabled, followed by the `tls.certificates.secrets` entries.
*/}}
{{- define "gateway.tlsSecretNames" -}}
{{- $names := list }}
{{- if include "gateway.tlsEngine" . }}
{{- $names = append $names (include "gateway.tlsAutoGeneratedSecretName" .) }}
{{- end }}
{{- $names = concat $names (include "gateway.tlsProvidedSecretNames" . | fromJsonArray) }}
{{- $names | toJson }}
{{- end }}

{{/*
Resolve the TLS provisioning engine from `tls.certificates.autoGenerated`.
Returns one of: "" (disabled, use `tls.certificates.secrets`), "helm", "cert-manager".
The engine is cert-manager when `tls.certificates.autoGenerated.certManager.enabled` is true;
otherwise helm.
*/}}
{{- define "gateway.tlsEngine" -}}
{{- with .Values.tls.certificates.autoGenerated -}}
{{- if .enabled -}}
{{- $cm := .certManager -}}
{{- if and $cm $cm.enabled -}}cert-manager{{- else -}}helm{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Return "true" when the TLS provisioning engine is Helm.
*/}}
{{- define "gateway.tlsEngineIsHelm" -}}
{{- if eq (include "gateway.tlsEngine" .) "helm" -}}
true
{{- end -}}
{{- end -}}

{{/*
Return "true" when the TLS provisioning engine is cert-manager.
*/}}
{{- define "gateway.tlsEngineIsCertManager" -}}
{{- if eq (include "gateway.tlsEngine" .) "cert-manager" -}}
true
{{- end -}}
{{- end -}}


{{/*
Create the name of the ConfigMap holding the inline `upstreamCABundles` PEM bundles
*/}}
{{- define "gateway.upstreamCABundlesConfigMapName" -}}
{{- printf "%s-upstream-ca-bundles" (include "gateway.fullname" .) }}
{{- end }}

{{/*
ConfigMap key for an inline `pem` bundle, derived from its position in `upstreamCABundles`.
*/}}
{{- define "gateway.upstreamCABundleInlineKey" -}}
{{- printf "ca%d.crt" . }}
{{- end }}

{{/*
Resolve each `upstreamCABundles` entry to the ConfigMap name and key holding its PEM.
Entries with `configMapName` are returned as given, defaulting the key to `ca.crt`.
Inline `pem` entries point at the chart-owned ConfigMap, keyed `ca<index>.crt`.

Returns a JSON array of {configMapName, key} objects, because include can only
return a string; callers decode it with fromJsonArray.
*/}}
{{- define "gateway.upstreamCABundleSources" -}}
{{- $sources := list }}
{{- range $i, $bundle := .Values.upstreamCABundles }}
{{- if $bundle.configMapName }}
{{- $sources = append $sources (dict "configMapName" $bundle.configMapName "key" ($bundle.configMapKey | default "ca.crt")) }}
{{- else if $bundle.pem }}
{{- $sources = append $sources (dict "configMapName" (include "gateway.upstreamCABundlesConfigMapName" $) "key" (include "gateway.upstreamCABundleInlineKey" $i)) }}
{{- end }}
{{- end }}
{{- $sources | toJson }}
{{- end }}

{{/*
Create the name of the SSH manual CA secret to use
*/}}
{{- define "gateway.sshManualCASecretName" -}}
{{- if .Values.ssh.ca.manual.existingSecret }}
{{- .Values.ssh.ca.manual.existingSecret }}
{{- else }}
{{- printf "%s-ssh-manual-ca" (include "gateway.fullname" .) }}
{{- end }}
{{- end }}

{{/*
Create the name of the SSH Vault CA bundle secret to use
*/}}
{{- define "gateway.sshVaultCABundleSecretName" -}}
{{- if and .Values.ssh.ca.vault .Values.ssh.ca.vault.existingCABundleSecret }}
{{- .Values.ssh.ca.vault.existingCABundleSecret }}
{{- else }}
{{- printf "%s-ssh-vault-ca-bundle" (include "gateway.fullname" .) }}
{{- end }}
{{- end }}

{{/*
Create the name of the SSH Vault token secret to use
*/}}
{{- define "gateway.sshVaultTokenSecretName" -}}
{{- if and .Values.ssh.ca.vault .Values.ssh.ca.vault.auth.existingTokenSecret }}
{{- .Values.ssh.ca.vault.auth.existingTokenSecret }}
{{- else }}
{{- printf "%s-ssh-vault-token" (include "gateway.fullname" .) }}
{{- end }}
{{- end }}

{{/*
Create the name of the SSH Vault AppRole secret ID secret to use
*/}}
{{- define "gateway.sshVaultAppRoleSecretIdSecretName" -}}
{{- if and .Values.ssh.ca.vault .Values.ssh.ca.vault.auth.appRole .Values.ssh.ca.vault.auth.appRole.existingSecretIdSecret }}
{{- .Values.ssh.ca.vault.auth.appRole.existingSecretIdSecret }}
{{- else }}
{{- printf "%s-ssh-vault-approle-secret-id" (include "gateway.fullname" .) }}
{{- end }}
{{- end }}


{{/*
Return the UID of the kube-system namespace, or "" when it cannot be read
*/}}
{{- define "gateway.clusterUID" -}}
{{- $namespace := lookup "v1" "Namespace" "" "kube-system" }}
{{- if and $namespace $namespace.metadata }}
{{- $namespace.metadata.uid }}
{{- end }}
{{- end }}

{{/*
Create the name the TwingateCertificateAuthority is registered under in Twingate

Twingate rejects duplicate Certificate Authority names and the CR's `spec.name` is
immutable, so separate installs must not derive the same name. kube-system's UID stands
in for the cluster because Helm renders before `--create-namespace` creates the release
namespace, so the release namespace's own UID is not always readable.
*/}}
{{- define "gateway.certificateAuthorityName" -}}
{{- $certificateAuthority := .Values.twingateOperator.gateway.certificateAuthority | default dict }}
{{- if $certificateAuthority.name }}
{{- $certificateAuthority.name }}
{{- else }}
{{- $clusterUID := include "gateway.clusterUID" . }}
{{- if not $clusterUID }}
{{- fail "Set twingateOperator.gateway.certificateAuthority.name to a name unique within your Twingate network. The chart derives one from the kube-system namespace UID, which is unavailable when rendering without cluster access such as helm template, --dry-run=client or Argo CD." }}
{{- end }}
{{- printf "%s-ca-%s" (include "gateway.fullname" .) (sha256sum (printf "%s/%s" $clusterUID .Release.Namespace) | trunc 16) }}
{{- end }}
{{- end }}

{{/*
Return "true" when a CA certificate is provided under twingateOperator.gateway.certificateAuthority,
either inline or as an existing Secret.
*/}}
{{- define "gateway.certificateAuthorityCertificateProvided" -}}
{{- $certificateAuthority := .Values.twingateOperator.gateway.certificateAuthority | default dict }}
{{- if or $certificateAuthority.certificate $certificateAuthority.certificateSecretName -}}
true
{{- end -}}
{{- end -}}

{{/*
Create the name of the Secret holding the CA certificate the TwingateCertificateAuthority registers.
*/}}
{{- define "gateway.certificateAuthoritySecretName" -}}
{{- $certificateAuthority := .Values.twingateOperator.gateway.certificateAuthority | default dict }}
{{- if $certificateAuthority.certificateSecretName }}
{{- $certificateAuthority.certificateSecretName }}
{{- else }}
{{- printf "%s-ca" (include "gateway.fullname" .) }}
{{- end }}
{{- end }}

{{/*
Fail when the TwingateCertificateAuthority would have no secretRef: the Gateway serves no
certificate Secret and no CA is provided under twingateOperator.gateway.certificateAuthority.
*/}}
{{- define "gateway.requireCASecret" -}}
{{- if and (not (include "gateway.tlsSecretNames" . | fromJsonArray)) (not (include "gateway.certificateAuthorityHasCertificate" .)) }}
{{- fail "The TwingateCertificateAuthority has no CA certificate to register. Set twingateOperator.gateway.certificateAuthority.certificate to the tls.automation issuer's CA certificate, or point twingateOperator.gateway.certificateAuthority.certificateSecretName at a Secret holding it under ca.crt." }}
{{- end }}
{{- end }}


{{/*
Get the alias of the in-cluster Kubernetes resource
*/}}
{{- define "gateway.resourceAlias" -}}
{{- with .Values.twingateOperator.kubernetesResource }}
{{- if .enabled }}
{{- .alias | default "" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
DNS names for the Gateway's TLS certificate, as a JSON array since include returns a string.
Callers decode it with fromJsonArray.

When the Gateway's Kubernetes proxy is enabled (`twingateOperator.kubernetesResource.enabled`
or `kubernetes.enabled`), the DNS names of the built-in `kubernetes` Service are added
automatically.
*/}}
{{- define "gateway.tlsDnsNames" -}}
{{- $dnsNames := .Values.tls.certificates.autoGenerated.dnsNames | default list }}
{{- $k8sResourceEnabled := and .Values.twingateOperator.kubernetesResource .Values.twingateOperator.kubernetesResource.enabled }}
{{- $k8sEnabled := and .Values.kubernetes .Values.kubernetes.enabled }}
{{- if or $k8sResourceEnabled $k8sEnabled }}
{{- $dnsNames = concat $dnsNames (list "kubernetes" "kubernetes.default" "kubernetes.default.svc" (printf "kubernetes.default.svc.%s" .Values.clusterDomain)) }}
{{- end }}
{{- $resourceAlias := include "gateway.resourceAlias" . }}
{{- if $resourceAlias }}
{{- $dnsNames = append $dnsNames $resourceAlias }}
{{- end }}
{{- $dnsNames | toJson }}
{{- end }}

{{/*
Fail when the certificate the chart would issue covers no name.
*/}}
{{- define "gateway.requireTlsNames" -}}
{{- if and (not (include "gateway.tlsDnsNames" . | fromJsonArray)) (not .Values.tls.certificates.autoGenerated.ipAddresses) }}
{{- fail "The Gateway's certificate would cover no Resource address. Set tls.certificates.autoGenerated.dnsNames or tls.certificates.autoGenerated.ipAddresses to the addresses of the Twingate Resources this Gateway serves." }}
{{- end }}
{{- end }}

{{/*
Fail when no TLS certificate or automation is configured.
*/}}
{{- define "gateway.requireTlsCertificates" -}}
{{- if and (not (include "gateway.tlsSecretNames" . | fromJsonArray)) (not .Values.tls.automation.enabled) }}
{{- fail "The Gateway needs at least one certificate. Set tls.certificates.autoGenerated.enabled to true, add an entry to tls.certificates.secrets, or set tls.automation.enabled to true." }}
{{- end }}
{{- end }}

{{/*
Create the alternative names hash of the TLS secret
*/}}
{{- define "gateway.alternativeNamesHash" -}}
{{- printf "%s-%s" .Values.tls.certificates.autoGenerated.ipAddresses (include "gateway.tlsDnsNames" .) | sha256sum }}
{{- end }}

{{/*
Create the existing alternative names hash of the TLS secret
*/}}
{{- define "gateway.existingAlternativeNamesHash" -}}
{{- if include "gateway.tlsEngineIsHelm" . }}
{{- $secretName := include "gateway.tlsAutoGeneratedSecretName" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if and $existingSecret $existingSecret.metadata $existingSecret.metadata.annotations }}
{{- get $existingSecret.metadata.annotations "checksum/alternativeNames" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create the Twingate host
*/}}
{{- define "gateway.twingate.host" -}}
{{- default "twingate.com" .Values.twingate.host }}
{{- end }}


{{/*
Create the Certificate Authority singleton

Generate CA object and stored the singleton value in .Values._generatedCA.
Caller should use .Values._generatedCA after calling this template.
*/}}
{{- define "gateway.generateCA" -}}
{{- if not .Values._generatedCA }}
{{- $ca := genCA (printf "%s-ca" (include "gateway.fullname" .)) 365 }}
{{- $_ := set .Values "_generatedCA" $ca }}
{{- end }}
{{- end }}
