{{- if and .Values.ssh.enabled .Values.ssh.ca .Values.ssh.ca.local (not .Values.ssh.ca.local.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.sshLocalCASecretName" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  ca-private-key: {{ required "ssh.ca.local.privateKey is required" .Values.ssh.ca.local.privateKey | b64enc }}
{{- end }}
