{{- if and .Values.tls.automation.enabled .Values.tls.automation.issuer.local (not .Values.tls.automation.issuer.local.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.tlsLocalCASecretName" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ required "tls.automation.issuer.local.certificate is required" .Values.tls.automation.issuer.local.certificate | b64enc }}
  ca.key: {{ required "tls.automation.issuer.local.privateKey is required" .Values.tls.automation.issuer.local.privateKey | b64enc }}
{{- end }}
